mimetypes:
  text/html: html
  text/markdown: markdown
  text/plain: plain
site:
  host: dario.cat
  baseurl: https://dario.cat
  language: ca
  title: Dario Castañé
zas:
  deploy: .zas/deploy
  layout: .zas/layout.html
