mimetypes:
  text/html: html
  text/markdown: markdown
  text/plain: plain
site:
  baseurl: http://da.rio.hn
  language: ca
  title: Dario Castañé
zas:
  deploy: .zas/deploy
  layout: .zas/layout.html
