baseURL = "https://dario.im"
title = "Dario Castañé"
copyright = "2018 Dario Castañé - Creative Commons Attribution-ShareAlike 4.0 International License."

theme = "minimo"

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true

pygmentsCodefences = true

enableEmoji = true

defaultContentLanguage = "ca"

[params.info]
description = "Pirate, trollslayer, gopher, full stack engineer"
title404 = "404 Not Found"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.5998az64.css"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.settings]
dateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"]
hideSocialMenu = false
showReadingTime = true
taxonomyCloudShuffle = false
accentColor = "#572b85"

[params.sidebar]
enable = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about", "taxonomy_cloud", "languages"]

[params.opengraph.twitter]
page = "im_dario"

[params.seo]
titleSeparator = "|"

[params.social]
email = "i@dario.im"
github = "imdario"
linkedin = "im.dario"
twitter = "im_dario"
telegram = "im_dario"

[taxonomies]
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true

[languages]
[languages.ca]
lang = "ca"
languageName = "Català"
weight = 1
copyright = "2018 Dario Castañé - Reconeixement-CompartirIgual 4.0 Internacional (CC BY-SA 4.0)"

[languages.es]
lang = "es"
languageName = "Castellano"
weight = 2
copyright = "2018 Dario Castañé - Reconocimiento-CompartirIgual 4.0 Internacional (CC BY-SA 4.0)"

[languages.en]
lang = "en"
languageName = "English"
weight = 3

[[menu.main]]
name = "home"
identifier = "home"
url = "/"
weight = -500

[[languages.ca.menu.main]]
name = "Inici"
identifier = "home"
url = "/"
weight = -500

[[languages.es.menu.main]]
name = "Inicio"
identifier = "home"
url = "/es/"
weight = -500

[[languages.en.menu.main]]
name = "Home"
identifier = "home"
url = "/en/"
weight = -500

[[menu.main]]
name = "blog"
identifier = "blog"
url = "/posts/"
weight = -400

[[languages.ca.menu.main]]
name = "Blog"
identifier = "blog"
url = "/posts/"
weight = -400

[[languages.es.menu.main]]
name = "Blog"
identifier = "blog"
url = "/es/posts/"
weight = -400

[[languages.en.menu.main]]
name = "Blog"
identifier = "blog"
url = "/en/posts/"
weight = -400

#[[menu.main]]
#name = "Microblog"
#url = ""

#[[menu.main]]
#name = "Code"
#url = ""

#[[menu.main]]
#name = "Talks"
#url = ""

#[[menu.main]]
#name = "Press archive"
#url = ""

#[[menu.main]]
#name = "Contact"
#url = ""
